// Filelist
+incdir+$PRJ_ICDIR/src
$PRJ_ICDIR/src/decode_stream.sv
$PRJ_ICDIR/src/avail.sv
$PRJ_ICDIR/src/bitstream_controller.v
$PRJ_ICDIR/src/bitstream_ena_gen.v
$PRJ_ICDIR/src/cabac.v
$PRJ_ICDIR/src/cabac_bypass_decode_bin.v
$PRJ_ICDIR/src/cabac_decode_bin.v
$PRJ_ICDIR/src/cabac_terminate_decode_bin.v
$PRJ_ICDIR/src/cu.sv
$PRJ_ICDIR/src/dec_bin_cu.v
$PRJ_ICDIR/src/dec_bin_gt1_etc.v
$PRJ_ICDIR/src/dec_bin_sd.v
$PRJ_ICDIR/src/dec_bin_sig.v
$PRJ_ICDIR/src/dec_bin_xy_pref.v
$PRJ_ICDIR/src/defines.v
$PRJ_ICDIR/src/dp_fifo.v
$PRJ_ICDIR/src/dram.v
$PRJ_ICDIR/src/dram_dual_port.v
$PRJ_ICDIR/src/dram_mult_port.v
$PRJ_ICDIR/src/dram_simple_dual.v
$PRJ_ICDIR/src/filter_32.sv
$PRJ_ICDIR/src/filter_64.sv
$PRJ_ICDIR/src/inter_pred_chroma.sv
$PRJ_ICDIR/src/inter_pred_luma.sv
$PRJ_ICDIR/src/intra_pred_16.sv
$PRJ_ICDIR/src/intra_pred_32.sv
$PRJ_ICDIR/src/mult.v
$PRJ_ICDIR/src/multacc.v
$PRJ_ICDIR/src/multadd.v
$PRJ_ICDIR/src/mv.sv
$PRJ_ICDIR/src/pps.v
$PRJ_ICDIR/src/ram.v
$PRJ_ICDIR/src/ram_dual_port.v
$PRJ_ICDIR/src/ram_simple_dual.v
$PRJ_ICDIR/src/rbsp_buffer.v
$PRJ_ICDIR/src/rbsp_buffer_simple.v
$PRJ_ICDIR/src/read_nalu.v
$PRJ_ICDIR/src/rps.sv
$PRJ_ICDIR/src/scale.sv
$PRJ_ICDIR/src/shr.sv
$PRJ_ICDIR/src/slice_data.sv
$PRJ_ICDIR/src/slice_header.sv
$PRJ_ICDIR/src/sps.v
$PRJ_ICDIR/src/trans_quant_16.sv
$PRJ_ICDIR/src/trans_quant_32.sv
$PRJ_ICDIR/src/tu.sv
$PRJ_ICDIR/src/type_defs.sv
$PRJ_ICDIR/src/vps.v
