set dont_touch_networks {
    u_analog_top/ldo_io_set
    u_analog_top/bk_core_scp_out
    u_analog_top/aon_reg_resv
    u_analog_top/bg_en
    u_analog_top/bk_core_clk_sel
    u_analog_top/bk_core_comps_type
    u_analog_top/bk_core_eco_en
    u_analog_top/bk_core_en
    u_analog_top/bk_core_hiz_en
    u_analog_top/bk_core_mode_en
    u_analog_top/bk_core_mode_set
    u_analog_top/bk_core_ocp_adj
    u_analog_top/bk_core_ocp_en
    u_analog_top/bk_core_osc_en
    u_analog_top/bk_core_vo_adj2
    u_analog_top/bk_core_zcd_en
    u_analog_top/bk_gen_eco_en
    u_analog_top/bk_gen_en
    u_analog_top/bk_gen_mode_en
    u_analog_top/bk_gen_mode_set
    u_analog_top/bk_gen_ocp_en
    u_analog_top/bk_gen_osc_en
    u_analog_top/bk_gen_vo_adj2
    u_analog_top/core_iso
    u_analog_top/ldo_ana_en
    u_analog_top/ldo_ana_vref
    u_analog_top/ldo_dcxo_en
    u_analog_top/ldo_dcxo_trim
    u_analog_top/ldo_io_en
    u_analog_top/ldo_io_ocp_en
    u_analog_top/ldo_io_softstart_en
    u_analog_top/ldo_io_vref
    u_analog_top/ldo_rtn_en
    u_analog_top/ldo_rtn_vout_sel
    u_analog_top/rstn_int
    u_digital_top/u_aon_sys_pwr_wrap/anlg_ldo_io_set
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_core_scp_out
    u_digital_top/u_aon_sys_pwr_wrap/anlg_aon_reg_resv
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bg_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_core_clk_sel
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_core_comps_type
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_core_eco_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_core_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_core_hiz_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_core_mode_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_core_mode_set
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_core_ocp_adj
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_core_ocp_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_core_osc_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_core_vo_adj2
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_core_zcd_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_gen_eco_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_gen_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_gen_mode_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_gen_mode_set
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_gen_ocp_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_gen_osc_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_bk_gen_vo_adj2
    u_digital_top/u_aon_sys_pwr_wrap/anlg_core_iso
    u_digital_top/u_aon_sys_pwr_wrap/anlg_ldo_ana_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_ldo_ana_vref
    u_digital_top/u_aon_sys_pwr_wrap/anlg_ldo_dcxo_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_ldo_dcxo_trim
    u_digital_top/u_aon_sys_pwr_wrap/anlg_ldo_io_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_ldo_io_ocp_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_ldo_io_softstart_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_ldo_io_vref
    u_digital_top/u_aon_sys_pwr_wrap/anlg_ldo_rtn_en
    u_digital_top/u_aon_sys_pwr_wrap/anlg_ldo_rtn_vout_sel
    u_digital_top/u_aon_sys_pwr_wrap/rstn_int
    u_digital_top/u_aon_sys_pwr_wrap/ptest_en_aon
    u_digital_top/u_aon_sys_pwr_wrap/clk_rtc32k_aon
    u_digital_top/u_aon_sys_pwr_wrap/rst_aon_por_n
    u_digital_top/u_aon_sys_pwr_wrap/rtc_prescale_1ms
    u_digital_top/u_aon_sys_pwr_wrap/rtc_prescale_1ms_busy
    u_digital_top/u_aon_sys_pwr_wrap/aon_deep_sleep_req
    u_digital_top/u_aon_sys_pwr_wrap/aon_deep_sleep_hold_exter
    u_digital_top/u_aon_sys_pwr_wrap/top_iso_en
    u_digital_top/u_aon_sys_pwr_wrap/alarm_irq
    u_digital_top/u_aon_sys_pwr_wrap/rc32k_cali_irq
    u_digital_top/u_aon_sys_pwr_wrap/rc32k_cali_done
    u_digital_top/u_aon_sys_pwr_wrap/rc32k_cali_trig
    u_digital_top/u_aon_sys_pwr_wrap/aon_root_clk_en
    u_digital_top/u_aon_sys_pwr_wrap/rtc2aon_wak_pbint
    u_digital_top/u_aon_sys_pwr_wrap/rtc2aon_wak_vbus
    u_digital_top/u_aon_sys_pwr_wrap/rtc2aon_wak_pwr
    u_digital_top/u_aon_sys_pwr_wrap/rtc2aon_wak_rstkey_deassert
    u_digital_top/u_aon_sys_pwr_wrap/rstn_int_dbnc
    u_digital_top/u_aon_sys_pwr_wrap/clk_rstkey_dbnc
    u_digital_top/u_aon_sys_pwr_wrap/rst_rstkey_dbnc_n
    u_digital_top/u_aon_sys_pwr_wrap/rstkey_dbnc_start
    u_digital_top/u_aon_sys_pwr_wrap/rstkey_dbnc_int_en
    u_digital_top/u_aon_sys_pwr_wrap/rstkey_dbnc_int_clr
    u_digital_top/u_aon_sys_pwr_wrap/rstkey_op_aon
    u_digital_top/u_aon_sys_pwr_wrap/rst_key_n_aon
    u_digital_top/u_aon_sys_pwr_wrap/rstkey_mask
    u_digital_top/u_aon_sys_pwr_wrap/rstkey_root_clk_en_aon
    u_digital_top/u_aon_sys_pwr_wrap/rstkey_iso_en_aon
    u_digital_top/u_aon_sys_pwr_wrap/force_turnoff_aon
    u_digital_top/u_aon_sys_pwr_wrap/intc_src_mask_aon
    u_digital_top/u_aon_sys_pwr_wrap/aon2rtc_dummy
    u_digital_top/u_aon_sys_pwr_wrap/rtc2aon_dummy
}
    foreach mnet $dont_touch_networks {
        set_dont_touch [get_nets -of [get_pins  $mnet]]
    }
