set dont_touch_networks {
    u_analog_top/xo32k_ready
    u_analog_top/aon_iso
    u_analog_top/ldo_aonio_en
    u_analog_top/ldo_rtc_aon_en
    u_analog_top/rc32k_enb
    u_analog_top/rc32k_flt_sel
    u_analog_top/rc32k_freq_trim
    u_analog_top/rc32k_op_itrim
    u_analog_top/rtc_itrim
    u_analog_top/rtc_virtual_loading0p8
    u_analog_top/rtc_virtual_loading1p8
    u_analog_top/rtc_vtrim0p8
    u_analog_top/rtc_vtrim1p8
    u_analog_top/xo32k_ctrl
    u_analog_top/xo32k_enb
    u_analog_top/xo32k_short_en
    u_analog_top/rtc_por_b
    u_analog_top/rtc32k_clk
    u_analog_top/pb_int
    u_analog_top/vbus_int
    u_analog_top/ptest_en
    u_digital_top/u_xmw_rtc_pwr_wrap/anlg_xo32k_ready
    u_digital_top/u_xmw_rtc_pwr_wrap/anlg_aon_iso
    u_digital_top/u_xmw_rtc_pwr_wrap/anlg_ldo_aonio_en
    u_digital_top/u_xmw_rtc_pwr_wrap/anlg_ldo_rtc_aon_en 
    u_digital_top/u_xmw_rtc_pwr_wrap/anlg_rc32k_enb
    u_digital_top/u_xmw_rtc_pwr_wrap/anlg_rc32k_flt_sel
    u_digital_top/u_xmw_rtc_pwr_wrap/anlg_rc32k_freq_trim
    u_digital_top/u_xmw_rtc_pwr_wrap/anlg_rc32k_op_itrim 
    u_digital_top/u_xmw_rtc_pwr_wrap/anlg_rtc_itrim
    u_digital_top/u_xmw_rtc_pwr_wrap/anlg_rtc_virtual_loading0p8
    u_digital_top/u_xmw_rtc_pwr_wrap/anlg_rtc_virtual_loading1p8
    u_digital_top/u_xmw_rtc_pwr_wrap/anlg_rtc_vtrim0p8
    u_digital_top/u_xmw_rtc_pwr_wrap/anlg_rtc_vtrim1p8
    u_digital_top/u_xmw_rtc_pwr_wrap/anlg_xo32k_ctrl
    u_digital_top/u_xmw_rtc_pwr_wrap/anlg_xo32k_enb
    u_digital_top/u_xmw_rtc_pwr_wrap/anlg_xo32k_short_en
    u_digital_top/u_xmw_rtc_pwr_wrap/rtc_por_b
    u_digital_top/u_xmw_rtc_pwr_wrap/rtc32k_clk
    u_digital_top/u_xmw_rtc_pwr_wrap/pb_int
    u_digital_top/u_xmw_rtc_pwr_wrap/vbus_int
    u_digital_top/u_xmw_rtc_pwr_wrap/ptest_en
    u_digital_top/u_xmw_rtc_pwr_wrap/ptest_en_aon
    u_digital_top/u_xmw_rtc_pwr_wrap/clk_rtc32k_aon
    u_digital_top/u_xmw_rtc_pwr_wrap/rst_aon_por_n
    u_digital_top/u_xmw_rtc_pwr_wrap/rtc_prescale_1ms
    u_digital_top/u_xmw_rtc_pwr_wrap/rtc_prescale_1ms_busy
    u_digital_top/u_xmw_rtc_pwr_wrap/aon_deep_sleep_req
    u_digital_top/u_xmw_rtc_pwr_wrap/aon_deep_sleep_hold_exter
    u_digital_top/u_xmw_rtc_pwr_wrap/top_iso_en
    u_digital_top/u_xmw_rtc_pwr_wrap/alarm_irq
    u_digital_top/u_xmw_rtc_pwr_wrap/rc32k_cali_irq
    u_digital_top/u_xmw_rtc_pwr_wrap/rc32k_cali_done
    u_digital_top/u_xmw_rtc_pwr_wrap/rc32k_cali_trig
    u_digital_top/u_xmw_rtc_pwr_wrap/aon_root_clk_en
    u_digital_top/u_xmw_rtc_pwr_wrap/rtc2aon_wak_pbint
    u_digital_top/u_xmw_rtc_pwr_wrap/rtc2aon_wak_vbus
    u_digital_top/u_xmw_rtc_pwr_wrap/rtc2aon_wak_pwr
    u_digital_top/u_xmw_rtc_pwr_wrap/rtc2aon_wak_rstkey_deassert
    u_digital_top/u_xmw_rtc_pwr_wrap/rstn_int_dbnc
    u_digital_top/u_xmw_rtc_pwr_wrap/clk_rstkey_dbnc
    u_digital_top/u_xmw_rtc_pwr_wrap/rst_rstkey_dbnc_n
    u_digital_top/u_xmw_rtc_pwr_wrap/rstkey_dbnc_start
    u_digital_top/u_xmw_rtc_pwr_wrap/rstkey_dbnc_int_en
    u_digital_top/u_xmw_rtc_pwr_wrap/rstkey_dbnc_int_clr
    u_digital_top/u_xmw_rtc_pwr_wrap/rstkey_op_aon
    u_digital_top/u_xmw_rtc_pwr_wrap/rst_key_n_aon
    u_digital_top/u_xmw_rtc_pwr_wrap/rstkey_mask
    u_digital_top/u_xmw_rtc_pwr_wrap/rstkey_root_clk_en_aon
    u_digital_top/u_xmw_rtc_pwr_wrap/rstkey_iso_en_aon
    u_digital_top/u_xmw_rtc_pwr_wrap/force_turnoff_aon
    u_digital_top/u_xmw_rtc_pwr_wrap/intc_src_mask_aon
    u_digital_top/u_xmw_rtc_pwr_wrap/aon2rtc_dummy
    u_digital_top/u_xmw_rtc_pwr_wrap/rtc2aon_dummy
}
    foreach mnet $dont_touch_networks {
        set_dont_touch  [get_nets -of [get_pins  $mnet]]
    }
