set period_clk_arm_mux $CYCLE_491M52
set period_clk_top_ahb $CYCLE_102M4
set period_clk_ap_ahb $CYCLE_204M8
set period_clk_cp_ahb $CYCLE_245M76
set period_clk_sys_ram $CYCLE_245M76
set period_clk_pub_ahb $CYCLE_204M8
set period_clk_flash_ahb $CYCLE_307M2
set period_clk_scan_clk $CYCLE_26M
####################################################################################################################
#JTAG IO delay
set_input_delay  [expr 0.7 * $CYCLE_26M] -clock  $name_clk_cpu_mtck_pad_in  -add_delay [get_ports    SWDITMS ]
set_output_delay [expr 0.6 * $CYCLE_26M] -clock  $name_clk_cpu_mtck_pad_in  -add_delay [get_ports    SWDO ]
set_output_delay [expr 0.6 * $CYCLE_26M] -clock  $name_clk_cpu_mtck_pad_in  -add_delay [get_ports    SWDOEN ]

##QSPI IO delay
##rise edge
#set_output_delay [expr 0.25 * $period_clk_arm_mux] -max -clock cpu_sys_QSPI_SCK -add_delay [get_ports QSPICSn]
#set_output_delay [expr 0.25 * $period_clk_arm_mux] -max -clock cpu_sys_QSPI_SCK -add_delay [get_ports QSPIDO]
#set_output_delay [expr 0.25 * $period_clk_arm_mux] -max -clock cpu_sys_QSPI_SCK -add_delay [get_ports QSPIDOEN]
#set_input_delay  [expr 0.25 * $period_clk_arm_mux] -max -clock cpu_sys_QSPI_SCK -add_delay [get_ports QSPIDI]
##fall edge
#set_output_delay [expr 0.25 * $period_clk_arm_mux] -max -clock  cpu_sys_QSPI_SCK -clock_fall -add_delay [get_ports QSPICSn]
#set_output_delay [expr 0.25 * $period_clk_arm_mux] -max -clock  cpu_sys_QSPI_SCK -clock_fall -add_delay [get_ports QSPIDO]
#set_output_delay [expr 0.25 * $period_clk_arm_mux] -max -clock  cpu_sys_QSPI_SCK -clock_fall -add_delay [get_ports QSPIDOEN]
#set_input_delay  [expr 0.25 * $period_clk_arm_mux] -max -clock  cpu_sys_QSPI_SCK -clock_fall -add_delay [get_ports QSPIDI]
#####################################################################################################################


set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports    DBGEN ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports    SPIDEN ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports    NIDEN ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports    SPNIDEN ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports    EDBGRQ ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports    DBGRESTART ]
set_input_delay [expr 0.7  * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports    DAPEN ]
set_input_delay [expr 0.7  * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports    wdg_int ]
set_input_delay [expr 0.7  * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports    ext_irq ]
set_input_delay [expr 0.7  * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports    INITNSVTOR]

set_input_delay  [expr 0.3 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports  cpusys_ram_slp_n     ]
set_input_delay  [expr 0.3 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports  cpusys_ram_dslp_n     ]
set_input_delay  [expr 0.3 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports  cpusys_ram_sd]
set_input_delay  [expr 0.3 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports  cpusys_rom_slp]
set_output_delay [expr 0.3 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports  cpusys_ram_sd_ack]

set_input_delay [expr 0.4 * $CYCLE_26M]  -clock cpu_sys_V_CLK_26M -add_delay  [get_ports   hw_en_clk_top_ahb]
set_input_delay [expr 0.4 * $CYCLE_26M]  -clock cpu_sys_V_CLK_26M -add_delay  [get_ports   hw_en_clk_sys_ram]
set_input_delay [expr 0.4 * $CYCLE_26M]  -clock cpu_sys_V_CLK_26M -add_delay  [get_ports   hw_en_clk_pub_ahb]
set_input_delay [expr 0.4 * $CYCLE_26M]  -clock cpu_sys_V_CLK_26M -add_delay  [get_ports   hw_en_clk_ap_ahb]
set_input_delay [expr 0.4 * $CYCLE_26M]  -clock cpu_sys_V_CLK_26M -add_delay  [get_ports   hw_en_clk_cp_ahb]
set_input_delay [expr 0.4 * $CYCLE_26M]  -clock cpu_sys_V_CLK_26M -add_delay  [get_ports   hw_en_clk_flash_ahb]



set_output_delay [expr 0.7 * $CYCLE_32K]    -clock $name_clk_cpu_arm_rtc                -add_delay [get_ports  busy_clk_32k_aon_cpu_sys]
set_output_delay [expr 0.7 * $CYCLE_26M]    -clock $name_clk_26m_xo_cpu_sys             -add_delay [get_ports  busy_clk_26m_xo_cpu_sys]
set_output_delay [expr 0.7 * $CYCLE_51M2]   -clock $name_clk_51_2m_cpll_cpu_sys         -add_delay [get_ports  busy_clk_51_2m_cpll_cpu_sys]
set_output_delay [expr 0.7 * $CYCLE_102M4]  -clock $name_clk_102_4m_cpll_cpu_sys        -add_delay [get_ports  busy_clk_102_4m_cpll_cpu_sys]
set_output_delay [expr 0.7 * $CYCLE_204M8]  -clock $name_clk_204_8m_cpll_cpu_sys        -add_delay [get_ports  busy_clk_204_8m_cpll_cpu_sys]
set_output_delay [expr 0.7 * $CYCLE_307M2]  -clock $name_clk_307_2m_cpll_cpu_sys        -add_delay [get_ports  busy_clk_307_2m_cpll_cpu_sys]
set_output_delay [expr 0.7 * $CYCLE_409M6]  -clock $name_clk_409_6m_cpll_cpu_sys        -add_delay [get_ports  busy_clk_409_6m_cpll_cpu_sys]
set_output_delay [expr 0.7 * $CYCLE_480M]   -clock $name_clk_480m_usbphy_pll_cpu_sys    -add_delay [get_ports  busy_clk_480m_usbphy_pll_cpu_sys]
set_output_delay [expr 0.7 * $CYCLE_491M52] -clock $name_clk_491_52m_cpll_cpu_sys       -add_delay [get_ports  busy_clk_491_52m_cpll_cpu_sys]
set_output_delay [expr 0.7 * $CYCLE_102M4]  -clock $name_clk_top_ahb                    -add_delay [get_ports  cgm_busy_clk_top_ahb]
set_output_delay [expr 0.7 * $CYCLE_204M8]  -clock $name_clk_pub_ahb                    -add_delay [get_ports  cgm_busy_clk_pub_ahb]
set_output_delay [expr 0.7 * $CYCLE_245M76] -clock $name_clk_sys_ram                    -add_delay [get_ports  cgm_busy_clk_sys_ram]
set_output_delay [expr 0.7 * $CYCLE_307M2]  -clock $name_clk_flash_ahb                  -add_delay [get_ports  cgm_busy_clk_flash_ahb]
set_output_delay [expr 0.7 * $CYCLE_245M76] -clock $name_clk_cp_ahb                     -add_delay [get_ports  cgm_busy_clk_cp_ahb]
set_output_delay [expr 0.7 * $CYCLE_204M8]  -clock $name_clk_ap_ahb                     -add_delay [get_ports  cgm_busy_clk_ap_ahb]
set_output_delay [expr 0.3 * $CYCLE_26M]    -clock $name_clk_cpu_mtck_pad_in            -add_delay [get_ports  cgm_busy_clk_cpu_mtck]

set_output_delay [expr 0.3 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports top2cpu_anti_ext]
set_output_delay [expr 0.3 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports ap2cpu_anti_ext]
set_output_delay [expr 0.3 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports cp2cpu_anti_ext]

set_input_delay  [expr 0.3 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay  [get_ports sw_cpu_main_mtx_rst]
set_input_delay  [expr 0.3 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay  [get_ports sw_ahb2ahba_top2cpu_rst]
set_input_delay  [expr 0.3 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay  [get_ports sw_ahb2ahba_ap2cpu_rst]
set_input_delay  [expr 0.3 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay  [get_ports sw_ahb2ahba_cp2cpu_rst]
set_input_delay  [expr 0.3 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay  [get_ports sw_ahb2ahba_cpu2flash_rst]

set_input_delay [expr 0.7 * $CYCLE_26M]    -clock cpu_sys_V_CLK_26M         -add_delay  [get_ports   cpu2top_anti_wakeup]
set_input_delay [expr 0.7 * $CYCLE_26M]    -clock cpu_sys_V_CLK_26M         -add_delay  [get_ports   cpu2sysram_anti_wakeup]
set_input_delay [expr 0.7 * $CYCLE_26M]    -clock cpu_sys_V_CLK_26M         -add_delay  [get_ports   cpu2pram_anti_wakeup]
set_input_delay [expr 0.7 * $CYCLE_26M]    -clock cpu_sys_V_CLK_26M         -add_delay  [get_ports   cpu2flash_anti_wakeup]
set_input_delay [expr 0.7 * $CYCLE_102M4]  -clock $name_clk_top_ahb         -add_delay  [get_ports  cpu2top_anti_ext]  
set_input_delay [expr 0.7 * $CYCLE_245M76] -clock $name_clk_sys_ram         -add_delay  [get_ports  cpu2sysram_anti_ext]
set_input_delay [expr 0.7 * $CYCLE_204M8]  -clock $name_clk_pub_ahb         -add_delay  [get_ports  cpu2pram_anti_ext]
set_input_delay [expr 0.7 * $CYCLE_307M2]  -clock $name_clk_flash_ahb       -add_delay  [get_ports  cpu2flash_anti_ext]


set_output_delay [expr 0.3 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M  -add_delay [get_ports  dbgbus_cpusys_data]

set_input_delay  [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay  [get_ports dbg_hready_cpu]
set_input_delay  [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay  [get_ports cpusys_dummy_in]
set_output_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay  [get_ports cpusys_dummy_out]

set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports CFGNSSTCALIB  ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports CFGFPU        ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports CFGDSP        ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports CFGSECEXT     ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports MPUNSDISABLE  ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports MPUSDISABLE   ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports SAUDISABLE    ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports CFGITCMSZ     ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports CFGDTCMSZ     ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports CFGMEMALIAS   ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports CFGNOCDECP    ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports INITTCMEN     ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports INITL1RSTDIS  ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports LOCKITGU      ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports LOCKDTGU      ]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports LOCKTCM       ]

set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports cpusys_shutdown_n]
set_output_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports cpusys_shutdown_ack_n]

set_input_delay [expr 0.5 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports rst_cpu_por_n]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports sw_arm_por_rst]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports sw_arm_sys_rst]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports sw_ahb2ahba_cpu2top_rst]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports sw_cfg_rst]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports sw_ahb2ahba_cpu2sysram_rst]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports sw_ahb2ahba_cpu2pub_rst]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports dbgbus_chain_sel]
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports ext_irq]  
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports CPUWAIT] 
set_input_delay [expr 0.7 * $CYCLE_26M] -clock cpu_sys_V_CLK_26M -add_delay [get_ports INSTANCEID ]
set_output_delay [expr 0.7 * $period_clk_arm_mux] -clock $name_clk_cpu_arm  -add_delay [get_ports     DBGRESTARTED ]
set_output_delay [expr 0.7 * $period_clk_arm_mux] -clock $name_clk_cpu_arm  -add_delay [get_ports cpusys_deep_sleep_req]
set_output_delay [expr 0.7 * $period_clk_arm_mux] -clock $name_clk_cpu_arm  -add_delay [get_ports SYSRESETREQ_rstcpusys]

  
set_output_delay  [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     top2cpu_HRDATAS                ]
set_output_delay  [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     top2cpu_HREADYOUTS             ]
set_output_delay  [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     top2cpu_HRESPS                 ]
set_input_delay   [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     top2cpu_HADDRS                 ]
set_input_delay   [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     top2cpu_HTRANSS                ]
set_input_delay   [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     top2cpu_HWRITES                ]
set_input_delay   [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     top2cpu_HSIZES                 ]
set_input_delay   [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     top2cpu_HBURSTS                ]
set_input_delay   [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     top2cpu_HPROTS                 ]
set_input_delay   [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     top2cpu_HWDATAS                ]
set_input_delay   [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     top2cpu_HMASTLOCKS             ]
set_input_delay   [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     top2cpu_HSELS                  ]
set_input_delay   [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     top2cpu_HREADYMUXS             ]

set_output_delay  [expr 0.7 * $period_clk_ap_ahb]  -clock $name_clk_ap_ahb -add_delay   [get_ports     ap2cpu_HRDATAS                ]
set_output_delay  [expr 0.7 * $period_clk_ap_ahb]  -clock $name_clk_ap_ahb -add_delay   [get_ports     ap2cpu_HREADYOUTS             ]
set_output_delay  [expr 0.7 * $period_clk_ap_ahb]  -clock $name_clk_ap_ahb -add_delay   [get_ports     ap2cpu_HRESPS                 ]
set_input_delay   [expr 0.7 * $period_clk_ap_ahb]  -clock $name_clk_ap_ahb -add_delay   [get_ports     ap2cpu_HADDRS                 ]
set_input_delay   [expr 0.7 * $period_clk_ap_ahb]  -clock $name_clk_ap_ahb -add_delay   [get_ports     ap2cpu_HTRANSS                ]
set_input_delay   [expr 0.7 * $period_clk_ap_ahb]  -clock $name_clk_ap_ahb -add_delay   [get_ports     ap2cpu_HWRITES                ]
set_input_delay   [expr 0.7 * $period_clk_ap_ahb]  -clock $name_clk_ap_ahb -add_delay   [get_ports     ap2cpu_HSIZES                 ]
set_input_delay   [expr 0.7 * $period_clk_ap_ahb]  -clock $name_clk_ap_ahb -add_delay   [get_ports     ap2cpu_HBURSTS                ]
set_input_delay   [expr 0.7 * $period_clk_ap_ahb]  -clock $name_clk_ap_ahb -add_delay   [get_ports     ap2cpu_HPROTS                 ]
set_input_delay   [expr 0.7 * $period_clk_ap_ahb]  -clock $name_clk_ap_ahb -add_delay   [get_ports     ap2cpu_HWDATAS                ]
set_input_delay   [expr 0.7 * $period_clk_ap_ahb]  -clock $name_clk_ap_ahb -add_delay   [get_ports     ap2cpu_HMASTLOCKS             ]
set_input_delay   [expr 0.7 * $period_clk_ap_ahb]  -clock $name_clk_ap_ahb -add_delay   [get_ports     ap2cpu_HAUSERS                ]
set_input_delay   [expr 0.7 * $period_clk_ap_ahb]  -clock $name_clk_ap_ahb -add_delay   [get_ports     ap2cpu_HSELS                  ]
set_input_delay   [expr 0.7 * $period_clk_ap_ahb]  -clock $name_clk_ap_ahb -add_delay   [get_ports     ap2cpu_HREADYMUXS             ]

set_output_delay  [expr 0.7 * $period_clk_cp_ahb]  -clock $name_clk_cp_ahb -add_delay   [get_ports     cp2cpu_HRDATAS                ]
set_output_delay  [expr 0.7 * $period_clk_cp_ahb]  -clock $name_clk_cp_ahb -add_delay   [get_ports     cp2cpu_HREADYOUTS             ]
set_output_delay  [expr 0.7 * $period_clk_cp_ahb]  -clock $name_clk_cp_ahb -add_delay   [get_ports     cp2cpu_HRESPS                 ]
set_input_delay   [expr 0.7 * $period_clk_cp_ahb]  -clock $name_clk_cp_ahb -add_delay   [get_ports     cp2cpu_HADDRS                 ]
set_input_delay   [expr 0.7 * $period_clk_cp_ahb]  -clock $name_clk_cp_ahb -add_delay   [get_ports     cp2cpu_HTRANSS                ]
set_input_delay   [expr 0.7 * $period_clk_cp_ahb]  -clock $name_clk_cp_ahb -add_delay   [get_ports     cp2cpu_HWRITES                ]
set_input_delay   [expr 0.7 * $period_clk_cp_ahb]  -clock $name_clk_cp_ahb -add_delay   [get_ports     cp2cpu_HSIZES                 ]
set_input_delay   [expr 0.7 * $period_clk_cp_ahb]  -clock $name_clk_cp_ahb -add_delay   [get_ports     cp2cpu_HBURSTS                ]
set_input_delay   [expr 0.7 * $period_clk_cp_ahb]  -clock $name_clk_cp_ahb -add_delay   [get_ports     cp2cpu_HPROTS                 ]
set_input_delay   [expr 0.7 * $period_clk_cp_ahb]  -clock $name_clk_cp_ahb -add_delay   [get_ports     cp2cpu_HWDATAS                ]
set_input_delay   [expr 0.7 * $period_clk_cp_ahb]  -clock $name_clk_cp_ahb -add_delay   [get_ports     cp2cpu_HMASTLOCKS             ]
set_input_delay   [expr 0.7 * $period_clk_cp_ahb]  -clock $name_clk_cp_ahb -add_delay   [get_ports     cp2cpu_HAUSERS                ]
set_input_delay   [expr 0.7 * $period_clk_cp_ahb]  -clock $name_clk_cp_ahb -add_delay   [get_ports     cp2cpu_HSELS                  ]
set_input_delay   [expr 0.7 * $period_clk_cp_ahb]  -clock $name_clk_cp_ahb -add_delay   [get_ports     cp2cpu_HREADYMUXS             ]

set_output_delay  [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     cpu2top_HADDRM                 ]
set_output_delay  [expr 0.5 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     cpu2top_HTRANSM                ]
set_output_delay  [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     cpu2top_HWRITEM                ]
set_output_delay  [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     cpu2top_HSIZEM                 ]
set_output_delay  [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     cpu2top_HBURSTM                ]
set_output_delay  [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     cpu2top_HPROTM                 ]
set_output_delay  [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     cpu2top_HWDATAM                ]
set_output_delay  [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     cpu2top_HMASTLOCKM             ]
set_input_delay   [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     cpu2top_HRDATAM                ]
set_input_delay   [expr 0.7 * $period_clk_top_ahb]  -clock $name_clk_top_ahb -add_delay [get_ports     cpu2top_HRESPM                 ]
set_input_delay   [expr 0.45 * $period_clk_top_ahb] -clock $name_clk_top_ahb -add_delay [get_ports     cpu2top_HREADYM                ]


set_output_delay  [expr 0.7 * $period_clk_sys_ram]  -clock $name_clk_sys_ram -add_delay [get_ports     cpu2sysram_HADDRM              ]
set_output_delay  [expr 0.7 * $period_clk_sys_ram]  -clock $name_clk_sys_ram -add_delay [get_ports     cpu2sysram_HTRANSM             ]
set_output_delay  [expr 0.7 * $period_clk_sys_ram]  -clock $name_clk_sys_ram -add_delay [get_ports     cpu2sysram_HWRITEM             ]
set_output_delay  [expr 0.7 * $period_clk_sys_ram]  -clock $name_clk_sys_ram -add_delay [get_ports     cpu2sysram_HSIZEM              ]
set_output_delay  [expr 0.7 * $period_clk_sys_ram]  -clock $name_clk_sys_ram -add_delay [get_ports     cpu2sysram_HBURSTM             ]
set_output_delay  [expr 0.7 * $period_clk_sys_ram]  -clock $name_clk_sys_ram -add_delay [get_ports     cpu2sysram_HPROTM              ]
set_output_delay  [expr 0.7 * $period_clk_sys_ram]  -clock $name_clk_sys_ram -add_delay [get_ports     cpu2sysram_HWDATAM             ]
set_output_delay  [expr 0.7 * $period_clk_sys_ram]  -clock $name_clk_sys_ram -add_delay [get_ports     cpu2sysram_HMASTLOCKM          ]
set_output_delay  [expr 0.7 * $period_clk_sys_ram]  -clock $name_clk_sys_ram -add_delay [get_ports     cpu2sysram_HAUSERM             ]
set_input_delay   [expr 0.7 * $period_clk_sys_ram]  -clock $name_clk_sys_ram -add_delay [get_ports     cpu2sysram_HRDATAM             ]
set_input_delay   [expr 0.7 * $period_clk_sys_ram]  -clock $name_clk_sys_ram -add_delay [get_ports     cpu2sysram_HRESPM              ]
set_input_delay   [expr 0.7 * $period_clk_sys_ram]  -clock $name_clk_sys_ram -add_delay [get_ports     cpu2sysram_HREADYM             ]

set_output_delay  [expr 0.7 * $period_clk_pub_ahb]  -clock $name_clk_pub_ahb -add_delay [get_ports     cpu2pram_HADDRM                ]
set_output_delay  [expr 0.7 * $period_clk_pub_ahb]  -clock $name_clk_pub_ahb -add_delay [get_ports     cpu2pram_HTRANSM               ]
set_output_delay  [expr 0.7 * $period_clk_pub_ahb]  -clock $name_clk_pub_ahb -add_delay [get_ports     cpu2pram_HWRITEM               ]
set_output_delay  [expr 0.7 * $period_clk_pub_ahb]  -clock $name_clk_pub_ahb -add_delay [get_ports     cpu2pram_HSIZEM                ]
set_output_delay  [expr 0.7 * $period_clk_pub_ahb]  -clock $name_clk_pub_ahb -add_delay [get_ports     cpu2pram_HBURSTM               ]
set_output_delay  [expr 0.7 * $period_clk_pub_ahb]  -clock $name_clk_pub_ahb -add_delay [get_ports     cpu2pram_HPROTM                ]
set_output_delay  [expr 0.7 * $period_clk_pub_ahb]  -clock $name_clk_pub_ahb -add_delay [get_ports     cpu2pram_HWDATAM               ]
set_output_delay  [expr 0.7 * $period_clk_pub_ahb]  -clock $name_clk_pub_ahb -add_delay [get_ports     cpu2pram_HMASTLOCKM            ]
set_output_delay  [expr 0.7 * $period_clk_pub_ahb]  -clock $name_clk_pub_ahb -add_delay [get_ports     cpu2pram_HAUSERM               ]
set_input_delay   [expr 0.7 * $period_clk_pub_ahb]  -clock $name_clk_pub_ahb -add_delay [get_ports     cpu2pram_HRDATAM               ]
set_input_delay   [expr 0.7 * $period_clk_pub_ahb]  -clock $name_clk_pub_ahb -add_delay [get_ports     cpu2pram_HRESPM                ]
set_input_delay   [expr 0.7 * $period_clk_pub_ahb]  -clock $name_clk_pub_ahb -add_delay [get_ports     cpu2pram_HREADYM               ]

set_output_delay  [expr 0.7 * $period_clk_flash_ahb]  -clock $name_clk_flash_ahb -add_delay [get_ports     cpu2flash_HADDRM                ]
set_output_delay  [expr 0.7 * $period_clk_flash_ahb]  -clock $name_clk_flash_ahb -add_delay [get_ports     cpu2flash_HTRANSM               ]
set_output_delay  [expr 0.7 * $period_clk_flash_ahb]  -clock $name_clk_flash_ahb -add_delay [get_ports     cpu2flash_HWRITEM               ]
set_output_delay  [expr 0.7 * $period_clk_flash_ahb]  -clock $name_clk_flash_ahb -add_delay [get_ports     cpu2flash_HSIZEM                ]
set_output_delay  [expr 0.7 * $period_clk_flash_ahb]  -clock $name_clk_flash_ahb -add_delay [get_ports     cpu2flash_HBURSTM               ]
set_output_delay  [expr 0.7 * $period_clk_flash_ahb]  -clock $name_clk_flash_ahb -add_delay [get_ports     cpu2flash_HPROTM                ]
set_output_delay  [expr 0.7 * $period_clk_flash_ahb]  -clock $name_clk_flash_ahb -add_delay [get_ports     cpu2flash_HWDATAM               ]
set_output_delay  [expr 0.7 * $period_clk_flash_ahb]  -clock $name_clk_flash_ahb -add_delay [get_ports     cpu2flash_HMASTLOCKM            ]
set_output_delay  [expr 0.7 * $period_clk_flash_ahb]  -clock $name_clk_flash_ahb -add_delay [get_ports     cpu2flash_HAUSERM               ]
set_input_delay   [expr 0.7 * $period_clk_flash_ahb]  -clock $name_clk_flash_ahb -add_delay [get_ports     cpu2flash_HRDATAM               ]
set_input_delay   [expr 0.7 * $period_clk_flash_ahb]  -clock $name_clk_flash_ahb -add_delay [get_ports     cpu2flash_HRESPM                ]
set_input_delay   [expr 0.7 * $period_clk_flash_ahb]  -clock $name_clk_flash_ahb -add_delay [get_ports     cpu2flash_HREADYM               ]
