if {! $IS_CHIP} {
    #aon io
    set_input_delay     [expr 0.3 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports  AONINT0]
    set_input_delay     [expr 0.3 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports  AONINT1]
    set_input_delay     [expr 0.3 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports  AONINT2]
    set_output_delay    [expr 0.3 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports  AONINT0]
    set_output_delay    [expr 0.3 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports  AONINT1]
    set_output_delay    [expr 0.3 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports  AONINT2]
    #analog
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports anlg_ldo_io_set]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports anlg_bk_core_scp_out]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_aon_reg_resv       ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bg_en              ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_core_clk_sel    ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_core_comps_type ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_core_eco_en     ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_core_en         ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_core_mode_en    ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_core_mode_set   ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_core_ocp_adj    ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_core_ocp_en     ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_core_osc_en     ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_core_vo_adj2    ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_core_zcd_en     ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_gen_eco_en      ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_gen_en          ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_gen_mode_en     ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_gen_mode_set    ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_gen_ocp_en      ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_gen_osc_en      ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_gen_vo_adj2     ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_core_iso           ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_ldo_ana_en         ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_ldo_ana_vref       ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_ldo_dcxo_en        ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_ldo_dcxo_trim      ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_ldo_io_en          ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_ldo_io_ocp_en      ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_ldo_io_softstart_en]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_ldo_io_vref        ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_ldo_rtn_en         ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_ldo_rtn_vout_sel   ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports anlg_bk_core_hiz_en     ]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports rstn_int]
    #rtc intf
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports ptest_en_aon]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports rst_aon_por_n]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports rtc_prescale_1ms]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports rtc_prescale_1ms_busy]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports aon_deep_sleep_req]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports aon_deep_sleep_hold_exter]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports top_iso_en]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports alarm_irq]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports rc32k_cali_irq]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports rc32k_cali_done]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports rc32k_cali_trig]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports aon_root_clk_en]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports rtc2aon_wak_pbint]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports rtc2aon_wak_vbus]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports rtc2aon_wak_pwr]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports rtc2aon_wak_rstkey_deassert]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rstkey_dbnc                  -add_delay [get_ports rstn_int_dbnc]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rstkey_dbnc                  -add_delay [get_ports rst_rstkey_dbnc_n]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rstkey_dbnc                  -add_delay [get_ports rstkey_dbnc_start]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rstkey_dbnc                  -add_delay [get_ports rstkey_dbnc_int_en]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rstkey_dbnc                  -add_delay [get_ports rstkey_dbnc_int_clr]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports rstkey_op_aon]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports rst_key_n_aon]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rstkey_dbnc                  -add_delay [get_ports rstkey_mask]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports rstkey_root_clk_en_aon]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports rstkey_iso_en_aon]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports force_turnoff_aon]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports intc_src_mask_aon]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports aon2rtc_dummy]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports rtc2aon_dummy]
    #top intf
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports ptest_en_top]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports ptest_mode_sel]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports rst_top_por_n]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_strappin                     -add_delay [get_ports rst_strappin]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports aon_psel  ]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports aon_penable]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports aon_pwrite]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports aon_paddr ]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports aon_pwdata]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports aon_prdata]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports aon_pready]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports ldo_dcxo_en]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports top_int_irq]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports top_deep_sleep_req]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports top_deep_sleep_hold_exter]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports top_deep_sleep_start]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports rc32k_cali_trig_top]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports rc32k_cali_done_top]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports rst_key_n_top]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports rstkey_iso_en_top]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports rstkey_root_clk_en_top]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports intc_src_mask_top]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_rtc32k_aon                   -add_delay [get_ports force_turnoff_top]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports bk_core_ocp_out]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports bk_gen_en_clr]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports ldo_io_en_clr]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports int_req_cdnsrtc ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_30_72m                       -add_delay [get_ports int_aon_frc ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports int_aon_eic ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports int_top_pwron ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports int_intc_req ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports int_aon_scp_alarm]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports frc_ratio_vld]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports frc_ratio_inte]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports frc_ratio_frac]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_30_72m                       -add_delay [get_ports cali_cpll_frac]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_30_72m                       -add_delay [get_ports cali_lenth_sel]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_30_72m                       -add_delay [get_ports aon_frc_cnt]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_30_72m                       -add_delay [get_ports gpio5_in   ]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports gpio5_out  ]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports gpio5_oen  ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports gpio6_in   ]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports gpio6_out  ]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports gpio6_oen  ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports gpio7_in   ]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports gpio7_out  ]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports gpio7_oen  ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports keyin1     ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports keyin4     ]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports keyout1    ]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports keyout1_OE ]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_30_72m                       -add_delay [get_ports busy_clk_30_72m_aon]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_aon_pmu_32k                  -add_delay [get_ports busy_clk_3_25m_aon]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_clk_xo26m_32k                    -add_delay [get_ports busy_clk_xo26m_32k_aon]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports rstn_int_chk]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports ldo_io_set_chk]
    set_input_delay     [expr 0.8 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports aon_frc_aux_en]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports dbgbus_aon_chain_sel]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports dbgbus_aon_data]
    set_input_delay     [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports top2aon_dummy]
    set_output_delay    [expr 0.4 * $CYCLE_32K]     -clock ${AON_SYS_NAME}_V_CLK_32K                        -add_delay [get_ports aon2top_dummy]
}
