set dont_touch_networks "
    ${CP_SYS_HIER}rxpll_ldo0p9_en              \
    ${CP_SYS_HIER}rxvco_ldo_en                 \
    ${CP_SYS_HIER}rxpll_vco_bias_en            \
    ${CP_SYS_HIER}rxpll_vco_en                 \
    ${CP_SYS_HIER}rxpll_dpll_rst_n             \
    ${CP_SYS_HIER}txpll_ldo0p9_en              \
    ${CP_SYS_HIER}txvco_ldo_en                 \
    ${CP_SYS_HIER}txpll_vco_bias_en            \
    ${CP_SYS_HIER}txpll_vco_en                 \
    ${CP_SYS_HIER}txpll_dpll_rst_n             \
    ${CP_SYS_HIER}rx_PWR_SATDET                \
    ${CP_SYS_HIER}rx_bb_PWR_BIAS               \
    ${CP_SYS_HIER}rx_bb_PWR_VCMREF             \
    ${CP_SYS_HIER}rx_lna_ldo_en                \
    ${CP_SYS_HIER}rx_ldo_en                    \
    ${CP_SYS_HIER}rx_lo_en                     \
    ${CP_SYS_HIER}rx_mix_p_en                  \
    ${CP_SYS_HIER}rx_mix_n_en                  \
    ${CP_SYS_HIER}rx_mix_resetb                \
    ${CP_SYS_HIER}rx_dcoc_en                   \
    ${CP_SYS_HIER}rx_i2v_en                    \
    ${CP_SYS_HIER}rx_fil1_en                   \
    ${CP_SYS_HIER}rx_fil2_en                   \
    ${CP_SYS_HIER}rx_pga_en                    \
    ${CP_SYS_HIER}rxadc_ldo_en                 \
    ${CP_SYS_HIER}rxadc_pu_i                   \
    ${CP_SYS_HIER}rxadc_pu_q                   \
    ${CP_SYS_HIER}txppa_ldo_en                 \
    ${CP_SYS_HIER}tx_bb_bias_en                \
    ${CP_SYS_HIER}txi2v_pwr                    \
    ${CP_SYS_HIER}dac_ldo_en                   \
    ${CP_SYS_HIER}txdac_en                     \
    ${CP_SYS_HIER}tx_ldo_en                    \
    ${CP_SYS_HIER}tx_lpf_en                    \
    ${CP_SYS_HIER}tx_lo_en                     \
    ${CP_SYS_HIER}tx_mix_en                    \
    ${CP_SYS_HIER}tx_mix_resetb                \
    ${CP_SYS_HIER}tx_ppa_bias_en               \
    ${CP_SYS_HIER}tx_ppa_en                    \
    ${CP_SYS_HIER}tx_pa_bias_en                \
    ${CP_SYS_HIER}tx_pa_en                     \
    ${CP_SYS_HIER}rx_Q_RCCAL                   \
    ${CP_SYS_HIER}rx_BA_C                      \
    ${CP_SYS_HIER}rx_BA_R                      \
    ${CP_SYS_HIER}rx_IB_FIL                    \
    ${CP_SYS_HIER}rx_BW_I2V                    \
    ${CP_SYS_HIER}rx_H_PREDEF_L_FREEDEF_I2V    \
    ${CP_SYS_HIER}rx_C_FREEDEF_LPF             \
    ${CP_SYS_HIER}rx_fil_bw                    \
    ${CP_SYS_HIER}txi2v_qrccal                 \
    ${CP_SYS_HIER}tx_bb_q_rccal                \
    ${CP_SYS_HIER}tx_lpf_h_predef_l_freedef    \
    ${CP_SYS_HIER}tx_lpf_freedef_cc            \
    ${CP_SYS_HIER}tx_lpf_rc_r1                 \
    ${CP_SYS_HIER}tx_lpf_rc_r3                 \
    ${CP_SYS_HIER}tx_fil_bw                    \
    ${CP_SYS_HIER}tx_ib_i2v                    \
    ${CP_SYS_HIER}tx_ib_fil                    \
    ${CP_SYS_HIER}tx_mod_h_hg_l_lg             \
    ${CP_SYS_HIER}txi2v_gain                   \
    ${CP_SYS_HIER}tx_lpf_gain_rc               \
    ${CP_SYS_HIER}tx_ppa_h_hg_l_lg             \
    ${CP_SYS_HIER}tx_ppa_gc_hg                 \
    ${CP_SYS_HIER}tx_ppa_gc_lg                 \
    ${CP_SYS_HIER}rxpll_en_gear_shift          \
    ${CP_SYS_HIER}rxpll_lpf_gear_shift_en      \
    ${CP_SYS_HIER}rxpll_lpf_fcal_filt_override \
    ${CP_SYS_HIER}rxpll_lpf_mux_ctrl           \
    ${CP_SYS_HIER}rxpll_lpf_c3_ctrl            \
    ${CP_SYS_HIER}rxpll_lpf_r3_ctrl            \
    ${CP_SYS_HIER}rxpll_lpf_c2_ctrl            \
    ${CP_SYS_HIER}rxpll_lpf_r1_ctrl            \
    ${CP_SYS_HIER}rxpll_lpf_c1_ctrl            \
    ${CP_SYS_HIER}txpll_en_gear_shift          \
    ${CP_SYS_HIER}txpll_lpf_gear_shift_en      \
    ${CP_SYS_HIER}txpll_lpf_fcal_filt_override \
    ${CP_SYS_HIER}txpll_lpf_mux_ctrl           \
    ${CP_SYS_HIER}txpll_lpf_c3_ctrl            \
    ${CP_SYS_HIER}txpll_lpf_r3_ctrl            \
    ${CP_SYS_HIER}txpll_lpf_c2_ctrl            \
    ${CP_SYS_HIER}txpll_lpf_r1_ctrl            \
    ${CP_SYS_HIER}txpll_lpf_c1_ctrl            \
    ${CP_SYS_HIER}rx_DCOS_POL_Q                \
    ${CP_SYS_HIER}rx_DCOS_POL_I                \
    ${CP_SYS_HIER}rx_DCOS_Q                    \
    ${CP_SYS_HIER}rx_DCOS_I                    \
    ${CP_SYS_HIER}rx_H_DIV4_L_DIV2_3           \
    ${CP_SYS_HIER}rx_H_DIV4_L_DIV2_4           \
    ${CP_SYS_HIER}rx_H_DIV4_L_DIV2_5           \
    ${CP_SYS_HIER}rx_MX_BAND_SEL               \
    ${CP_SYS_HIER}rx_MXBIAS_STEP               \
    ${CP_SYS_HIER}rx_LODC_INXN                 \
    ${CP_SYS_HIER}rx_LODC_INXP                 \
    ${CP_SYS_HIER}rx_LODC_IPXN                 \
    ${CP_SYS_HIER}rx_LODC_IPXP                 \
    ${CP_SYS_HIER}rxadc_en_clk                 \
    ${CP_SYS_HIER}tx_cal_en                    \
    ${CP_SYS_HIER}rx_iqcal_loopback_band_sel   \
    ${CP_SYS_HIER}tx_cal_att_tune              \
    ${CP_SYS_HIER}rx_rccal_rstn                \
    ${CP_SYS_HIER}rx_pwr_rccal      \
    ${CP_SYS_HIER}rx_hen_rccal      \
    ${CP_SYS_HIER}rx_ib_rccal_op    \
    ${CP_SYS_HIER}rx_ib_rccal_cm    \
    ${CP_SYS_HIER}rx_vb_rccal_cm    \
    ${CP_SYS_HIER}rx_ib_rccal_comp  \
    ${CP_SYS_HIER}tdd_rxpll_txpll_sw             \
    ${CP_SYS_HIER}tx_port_lb1_en                 \
    ${CP_SYS_HIER}tx_port_hmb1_en                \
    ${CP_SYS_HIER}tx_port_hmb2_en                \
    ${CP_SYS_HIER}tx_notch_filter_ctune          \
    ${CP_SYS_HIER}tx_ppa_ctune                  \
    ${CP_SYS_HIER}tx_logen_h_div4_l_div2         \
    ${CP_SYS_HIER}tx_ppa_band_sel                \
    ${CP_SYS_HIER}txpll_prediv                   \
    ${CP_SYS_HIER}rxpll_prediv                   \
    ${CP_SYS_HIER}rxvco_ldo_byp                  \
    ${CP_SYS_HIER}rxvco_ldo_opa_cs_buf           \
    ${CP_SYS_HIER}rxvco_ldo_opa_ib_bst           \
    ${CP_SYS_HIER}rxvco_ldo_opa_cs               \
    ${CP_SYS_HIER}rxvco_ldo_ref_off              \
    ${CP_SYS_HIER}rxvco_ldo_filt_en              \
    ${CP_SYS_HIER}rxvco_ldo_bleed                \
    ${CP_SYS_HIER}rxvco_ldo_fb                   \
    ${CP_SYS_HIER}rxpll_ldo0p9_byp               \
    ${CP_SYS_HIER}rxpll_ldo0p9_rz_ctrl           \
    ${CP_SYS_HIER}rxpll_ldo0p9_opa_ib_bst        \
    ${CP_SYS_HIER}rxpll_ldo0p9_opa_cs            \
    ${CP_SYS_HIER}rxpll_ldo0p9_ref_off           \
    ${CP_SYS_HIER}rxpll_ldo0p9_filt_en           \
    ${CP_SYS_HIER}rxpll_ldo0p9_bleed             \
    ${CP_SYS_HIER}rxpll_ldo0p9_fb                \
    ${CP_SYS_HIER}txvco_ldo_byp                  \
    ${CP_SYS_HIER}txvco_ldo_opa_cs_buf           \
    ${CP_SYS_HIER}txvco_ldo_opa_ib_bst           \
    ${CP_SYS_HIER}txvco_ldo_opa_cs               \
    ${CP_SYS_HIER}txvco_ldo_ref_off              \
    ${CP_SYS_HIER}txvco_ldo_filt_en              \
    ${CP_SYS_HIER}txvco_ldo_bleed                \
    ${CP_SYS_HIER}txvco_ldo_fb                   \
    ${CP_SYS_HIER}txpll_ldo0p9_byp               \
    ${CP_SYS_HIER}txpll_ldo0p9_rz_ctrl           \
    ${CP_SYS_HIER}txpll_ldo0p9_opa_ib_bst        \
    ${CP_SYS_HIER}txpll_ldo0p9_opa_cs            \
    ${CP_SYS_HIER}txpll_ldo0p9_ref_off           \
    ${CP_SYS_HIER}txpll_ldo0p9_filt_en           \
    ${CP_SYS_HIER}txpll_ldo0p9_bleed             \
    ${CP_SYS_HIER}txpll_ldo0p9_fb                \
    ${CP_SYS_HIER}rxpll_pfd_sel_enopt            \
    ${CP_SYS_HIER}rxpll_pfd_tdel                 \
    ${CP_SYS_HIER}rxpll_cp_opa_boost             \
    ${CP_SYS_HIER}rxpll_cp_mirror_size           \
    ${CP_SYS_HIER}rxpll_cp_iboost                \
    ${CP_SYS_HIER}rxpll_cp_biassel_bgcgm         \
    ${CP_SYS_HIER}rxpll_cp_ipcode                \
    ${CP_SYS_HIER}rxpll_cp_incode                \
    ${CP_SYS_HIER}txpll_pfd_sel_enopt            \
    ${CP_SYS_HIER}txpll_pfd_tdel                 \
    ${CP_SYS_HIER}txpll_cp_opa_boost             \
    ${CP_SYS_HIER}txpll_cp_mirror_size           \
    ${CP_SYS_HIER}txpll_cp_iboost                \
    ${CP_SYS_HIER}txpll_cp_biassel_bgcgm         \
    ${CP_SYS_HIER}txpll_cp_ipcode                \
    ${CP_SYS_HIER}txpll_cp_incode                \
    ${CP_SYS_HIER}rxpll_lpf_c3_pre               \
    ${CP_SYS_HIER}rxpll_lpf_r3_pre               \
    ${CP_SYS_HIER}rxpll_lpf_c2_pre               \
    ${CP_SYS_HIER}rxpll_lpf_r1_pre               \
    ${CP_SYS_HIER}rxpll_lpf_c1_pre               \
    ${CP_SYS_HIER}txpll_lpf_c3_pre               \
    ${CP_SYS_HIER}txpll_lpf_r3_pre               \
    ${CP_SYS_HIER}txpll_lpf_c2_pre               \
    ${CP_SYS_HIER}txpll_lpf_r1_pre               \
    ${CP_SYS_HIER}txpll_lpf_c1_pre               \
    ${CP_SYS_HIER}rxpll_dpll_rst_gate_b          \
    ${CP_SYS_HIER}rxpll_dpll_vco_ctrl_override   \
    ${CP_SYS_HIER}rxpll_dpll_done                \
    ${CP_SYS_HIER}rxpll_dpll_ideal_count         \
    ${CP_SYS_HIER}rxpll_dpll_ref_div             \
    ${CP_SYS_HIER}rxpll_vco_freq_override        \
    ${CP_SYS_HIER}txpll_dpll_rst_gate_b          \
    ${CP_SYS_HIER}txpll_dpll_vco_ctrl_override   \
    ${CP_SYS_HIER}txpll_dpll_done                \
    ${CP_SYS_HIER}txpll_dpll_ideal_count         \
    ${CP_SYS_HIER}txpll_dpll_ref_div             \
    ${CP_SYS_HIER}txpll_vco_freq_override        \
    ${CP_SYS_HIER}rxpll_ld_lock                  \
    ${CP_SYS_HIER}rxpll_ld_vh                    \
    ${CP_SYS_HIER}rxpll_ld_vl                    \
    ${CP_SYS_HIER}rxpll_lock_det_en              \
    ${CP_SYS_HIER}rxpll_lock_gate_vhi            \
    ${CP_SYS_HIER}rxpll_lock_gate_vlow           \
    ${CP_SYS_HIER}txpll_ld_lock                  \
    ${CP_SYS_HIER}txpll_ld_vh                    \
    ${CP_SYS_HIER}txpll_ld_vl                    \
    ${CP_SYS_HIER}txpll_lock_det_en              \
    ${CP_SYS_HIER}txpll_lock_gate_vhi            \
    ${CP_SYS_HIER}txpll_lock_gate_vlow           \
    ${CP_SYS_HIER}rxpll_vco_en_filt              \
    ${CP_SYS_HIER}rxpll_vco_vpbias_mode          \
    ${CP_SYS_HIER}rxpll_vco_bias_mode            \
    ${CP_SYS_HIER}rxpll_vco_var_sel              \
    ${CP_SYS_HIER}rxpll_vco_var                  \
    ${CP_SYS_HIER}rxpll_vco_en_ical              \
    ${CP_SYS_HIER}rxpll_vco_ical                 \
    ${CP_SYS_HIER}rxpll_vco_ibuf                 \
    ${CP_SYS_HIER}rxpll_vco_ib                   \
    ${CP_SYS_HIER}rxpll_vco_icore                \
    ${CP_SYS_HIER}rxpll_vco_read_freq            \
    ${CP_SYS_HIER}txpll_vco_en_filt              \
    ${CP_SYS_HIER}txpll_vco_vpbias_mode          \
    ${CP_SYS_HIER}txpll_vco_bias_mode            \
    ${CP_SYS_HIER}txpll_vco_var_sel              \
    ${CP_SYS_HIER}txpll_vco_var                  \
    ${CP_SYS_HIER}txpll_vco_en_ical              \
    ${CP_SYS_HIER}txpll_vco_ical                 \
    ${CP_SYS_HIER}txpll_vco_ibuf                 \
    ${CP_SYS_HIER}txpll_vco_ib                   \
    ${CP_SYS_HIER}txpll_vco_icore                \
    ${CP_SYS_HIER}txpll_vco_read_freq            \
    ${CP_SYS_HIER}rxadc_ldo_byp                  \
    ${CP_SYS_HIER}rxadc_ldo_opa_cs_buf           \
    ${CP_SYS_HIER}rxadc_ldo_rz_ctrl              \
    ${CP_SYS_HIER}rxadc_ldo_opa_ib_bst           \
    ${CP_SYS_HIER}rxadc_ldo_opa_cs               \
    ${CP_SYS_HIER}rxadc_ldo_ref_off              \
    ${CP_SYS_HIER}rxadc_ldo_filt_en              \
    ${CP_SYS_HIER}rxadc_ldo_bleed                \
    ${CP_SYS_HIER}rxadc_ldo_fb                   \
    ${CP_SYS_HIER}rxadc_del_ctr_ch1_i            \
    ${CP_SYS_HIER}rxadc_del_ctr_ch3_i            \
    ${CP_SYS_HIER}rxadc_del_ctr_ch1_q            \
    ${CP_SYS_HIER}rxadc_del_ctr_ch3_q            \
    ${CP_SYS_HIER}rx_ldo_byp                     \
    ${CP_SYS_HIER}rx_ldo_opa_cs_buf              \
    ${CP_SYS_HIER}rx_ldo_rz_ctrl                 \
    ${CP_SYS_HIER}rx_ldo_opa_ib_bst              \
    ${CP_SYS_HIER}rx_ldo_opa_cs                  \
    ${CP_SYS_HIER}rx_ldo_ref_off                 \
    ${CP_SYS_HIER}rx_ldo_filt_en                 \
    ${CP_SYS_HIER}rx_ldo_bleed                   \
    ${CP_SYS_HIER}rx_ldo_fb                      \
    ${CP_SYS_HIER}rxbb_rsv1                      \
    ${CP_SYS_HIER}rx_VTH_SEL                     \
    ${CP_SYS_HIER}rx_IB_SATDET                   \
    ${CP_SYS_HIER}rx_HEN_DCOS                    \
    ${CP_SYS_HIER}rx_IB_DCOS_REF                 \
    ${CP_SYS_HIER}rx_IB_I2V                      \
    ${CP_SYS_HIER}rx_IB_PGA                      \
    ${CP_SYS_HIER}rx_bb_VCM_SEL                  \
    ${CP_SYS_HIER}rx_H_PREDEF_L_FREEDEF_LPF      \
    ${CP_SYS_HIER}rx_C_FREEDEF_I2V               \
    ${CP_SYS_HIER}rx_H_FINE_L_COARSE             \
    ${CP_SYS_HIER}rx_LODC_COARSE                 \
    ${CP_SYS_HIER}rx_LODC_QNXN                   \
    ${CP_SYS_HIER}rx_LODC_QNXP                   \
    ${CP_SYS_HIER}rx_LODC_QPXN                   \
    ${CP_SYS_HIER}rx_LODC_QPXP                   \
    ${CP_SYS_HIER}tx_ldo_byp                     \
    ${CP_SYS_HIER}tx_ldo_opa_cs_buf              \
    ${CP_SYS_HIER}tx_ldo_rz_ctrl                 \
    ${CP_SYS_HIER}tx_ldo_ib_bst                  \
    ${CP_SYS_HIER}tx_ldo_opa_cs                  \
    ${CP_SYS_HIER}tx_ldo_ref_off                 \
    ${CP_SYS_HIER}tx_ldo_filt_en                 \
    ${CP_SYS_HIER}tx_ldo_bleed                   \
    ${CP_SYS_HIER}tx_ldo_vout_ctrl               \
    ${CP_SYS_HIER}txdac_clkendg_ctrl2            \
    ${CP_SYS_HIER}tx_lo_dc                       \
    ${CP_SYS_HIER}tx_mod_selfbias                \
    ${CP_SYS_HIER}tx_vcm_sel                     \
    ${CP_SYS_HIER}tx_ib_mod                      \
    ${CP_SYS_HIER}txbb_rsv3                      \
    ${CP_SYS_HIER}txmix_rsv1                     \
    ${CP_SYS_HIER}dac_ldo_byp                    \
    ${CP_SYS_HIER}dac_ldo_rz_ctrl                \
    ${CP_SYS_HIER}dac_ldo_opa_ib_bst             \
    ${CP_SYS_HIER}dac_ldo_opa_cs                 \
    ${CP_SYS_HIER}dac_ldo_ref_off                \
    ${CP_SYS_HIER}dac_ldo_filt_en                \
    ${CP_SYS_HIER}dac_ldo_bleed                  \
    ${CP_SYS_HIER}dac_ldo_fb                     \
    ${CP_SYS_HIER}txdac_clk_edge                 \
    ${CP_SYS_HIER}txdac_bias                     \
    ${CP_SYS_HIER}txdac_biasres                  \
    ${CP_SYS_HIER}txdac_load_res_i               \
    ${CP_SYS_HIER}txdac_half_mir                 \
    ${CP_SYS_HIER}txdac_inv_ck                   \
    ${CP_SYS_HIER}txdac_msb_tog                  \
    ${CP_SYS_HIER}txdac_load_res_q               \
    ${CP_SYS_HIER}rx_lna_ldo_byp                 \
    ${CP_SYS_HIER}rx_lna_ldo_opa_cs_buf          \
    ${CP_SYS_HIER}rx_lna_ldo_rz_ctrl             \
    ${CP_SYS_HIER}rx_lna_ldo_opa_ib_bst          \
    ${CP_SYS_HIER}rx_lna_ldo_opa_cs              \
    ${CP_SYS_HIER}rx_lna_ldo_ref_off             \
    ${CP_SYS_HIER}rx_lna_ldo_filt_en             \
    ${CP_SYS_HIER}rx_lna_ldo_bleed               \
    ${CP_SYS_HIER}rx_lna_ldo_fb                  \
    ${CP_SYS_HIER}rx_lna_pc_ascode_en            \
    ${CP_SYS_HIER}rx_lna_protect_en              \
    ${CP_SYS_HIER}rx_lna_cgm_sel                 \
    ${CP_SYS_HIER}rx_lna_bias                    \
    ${CP_SYS_HIER}txppa_ldo_byp                  \
    ${CP_SYS_HIER}txppa_ldo_opa_cs_buf           \
    ${CP_SYS_HIER}txppa_ldo_ib_bst           \
    ${CP_SYS_HIER}txppa_ldo_opa_cs               \
    ${CP_SYS_HIER}txppa_ldo_ref_off              \
    ${CP_SYS_HIER}txppa_ldo_filt_en              \
    ${CP_SYS_HIER}txppa_ldo_bleed                \
    ${CP_SYS_HIER}txppa_ldo_vout_ctrl            \
    ${CP_SYS_HIER}tx_ppa_vbcas_lg                \
    ${CP_SYS_HIER}tx_ppa_vbcas_hg                \
    ${CP_SYS_HIER}txppa_vbcore_lg                \
    ${CP_SYS_HIER}txppa_vbcore1_hg               \
    ${CP_SYS_HIER}txppa_vbcore2_hg               \
    ${CP_SYS_HIER}txpa3                          \
    ${CP_SYS_HIER}rxadc_ref_vadjI                \
    ${CP_SYS_HIER}rxadc_ref_vadjQ                \
    ${CP_SYS_HIER}rxadc_en_hspd                  \
    ${CP_SYS_HIER}Test_sel                       \
    ${CP_SYS_HIER}Test_block_sel                 \
    ${CP_SYS_HIER}satdet                         \
    ${CP_SYS_HIER}rx_rccal_q_cap                 \
    ${CP_SYS_HIER}SATDET_DIGOUT_PGA              \
    ${CP_SYS_HIER}SATDET_DIGOUT_I2V              \
    ${CP_SYS_HIER}spare1                         \
    ${CP_SYS_HIER}rxpll_ds_26m_clk                \
    ${CP_SYS_HIER}rxpll_mash_rst_n                \
    ${CP_SYS_HIER}txpll_ds_26m_clk                \
    ${CP_SYS_HIER}txpll_mash_rst_n                \
    ${CP_SYS_HIER}rxpll_en                     \
    ${CP_SYS_HIER}rxpll_mash_clk_sw              \
    ${CP_SYS_HIER}rxpll_mash2                    \
    ${CP_SYS_HIER}rxpll_mash_clk_en             \
    ${CP_SYS_HIER}rxpll_mash_dith_shape          \
    ${CP_SYS_HIER}rxpll_mash_dith_lsb            \
    ${CP_SYS_HIER}rxpll_mash_int_mode_en         \
    ${CP_SYS_HIER}rxpll_mash_update        \
    ${CP_SYS_HIER}rxpll_mash_select        \
    ${CP_SYS_HIER}rxpll_mash_int\
    ${CP_SYS_HIER}rxpll_mash_frac\
    ${CP_SYS_HIER}txpll_en                     \
    ${CP_SYS_HIER}txpll_mash_clk_sw              \
    ${CP_SYS_HIER}txpll_mash2                    \
    ${CP_SYS_HIER}txpll_mash_clk_en             \
    ${CP_SYS_HIER}txpll_mash_dith_shape          \
    ${CP_SYS_HIER}txpll_mash_dith_lsb            \
    ${CP_SYS_HIER}txpll_mash_int_mode_en         \
    ${CP_SYS_HIER}txpll_mash_update   \
    ${CP_SYS_HIER}txpll_mash_select        \
    ${CP_SYS_HIER}txpll_mash_int\
    ${CP_SYS_HIER}txpll_mash_frac\
    ${CP_SYS_HIER}rxadc_en_ch1_i                  \
    ${CP_SYS_HIER}rxadc_en_ch1_q                  \
    ${CP_SYS_HIER}rxadc_en_ch3_i                  \
    ${CP_SYS_HIER}rxadc_en_ch3_q                  \
    ${CP_SYS_HIER}rxadc_B1_i\
    ${CP_SYS_HIER}rxadc_B1_q\
    ${CP_SYS_HIER}rxadc_B3_i\
    ${CP_SYS_HIER}rxadc_B3_q\
    ${CP_SYS_HIER}rxadc_ready_ch1_i\
    ${CP_SYS_HIER}rxadc_ready_ch1_q\
    ${CP_SYS_HIER}rxadc_ready_ch3_i\
    ${CP_SYS_HIER}rxadc_ready_ch3_q\
    ${CP_SYS_HIER}rxadc_calp_ch1_i\
    ${CP_SYS_HIER}rxadc_calp_ch1_q\
    ${CP_SYS_HIER}rxadc_calp_ch3_i\
    ${CP_SYS_HIER}rxadc_calp_ch3_q\
    ${CP_SYS_HIER}rxadc_caln_ch1_i\
    ${CP_SYS_HIER}rxadc_caln_ch1_q\
    ${CP_SYS_HIER}rxadc_caln_ch3_i\
    ${CP_SYS_HIER}rxadc_caln_ch3_q\
    ${CP_SYS_HIER}rxadc_cal_dac_ctr_ch1_i\
    ${CP_SYS_HIER}rxadc_cal_dac_ctr_ch1_q\
    ${CP_SYS_HIER}rxadc_cal_dac_ctr_ch3_i\
    ${CP_SYS_HIER}rxadc_cal_dac_ctr_ch3_q\
    ${CP_SYS_HIER}tx_data_in_i\
    ${CP_SYS_HIER}tx_data_in_q\
    ${CP_SYS_HIER}rx_lna_cmatch\
    ${CP_SYS_HIER}rx_lna_gm           \
    ${CP_SYS_HIER}rx_lna_attn_tune\
    ${CP_SYS_HIER}rx_lna_rmatch       \
    ${CP_SYS_HIER}rx_lna_attn_stp     \
    ${CP_SYS_HIER}rx_i2v              \
    ${CP_SYS_HIER}rx_pga              \
    ${CP_SYS_HIER}rxadc_ck_sar_latch_i \
    ${CP_SYS_HIER}rxadc_ck_sar_latch_q \
    ${CP_SYS_HIER}rxadc_clk245m        \
    ${CP_SYS_HIER}clk_dig_122p88m      \
    ${CP_SYS_HIER}clk_dig_122p88m_en   \
    ${CP_SYS_HIER}rxadc_clk245m_en     \
"
foreach mnet $dont_touch_networks {
    set_dont_touch  [get_nets -of [get_pins  $mnet]]
}
