    set qspi_output_skew_list [list \
qspi_output_skew 0.8 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/tx_shift_reg_reg_32_/CP SF0_IO0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_do_o[0] None \
qspi_output_skew 0.8 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/qspi_do_en_o_reg_0_/CP SF0_IO0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_do_en_o[0] None \
qspi_output_skew 0.8 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/tx_shift_reg_reg_33_/CP SF0_IO1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_do_o[1] None \
qspi_output_skew 0.8 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/qspi_do_en_o_reg_1_/CP SF0_IO1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_do_en_o[1] None \
qspi_output_skew 0.8 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/tx_shift_reg_reg_34_/CP SF0_IO2 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_do_o[2] None \
qspi_output_skew 0.8 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/qspi_do_en_o_reg_2_/CP SF0_IO2 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_do_en_o[2] None \
qspi_output_skew 0.8 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/tx_shift_reg_reg_35_/CP SF0_IO3 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_do_o[3] None \
qspi_output_skew 0.8 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/qspi_do_en_o_reg_2_/CP SF0_IO3 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_do_en_o[3] None \
qspi_output_skew 0.8 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/fsm_cs_reg_0_/CP SF0_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_cs_n_o None \
qspi_output_skew 0.8 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/qspi_sck_o_pre_reg/CP SF0_SCK u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_sck_o None \
]

tproc_stc_skew_report $qspi_output_skew_list
tproc_stc_array2csv   $qspi_output_skew_list stc_check_skew.csv

    set qspi_output_data_skew_list [list \
qspi_output_data_skew 0.4 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/tx_shift_reg_reg_32_/CP SF0_IO0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_do_o[0] None \
qspi_output_data_skew 0.4 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/qspi_do_en_o_reg_0_/CP SF0_IO0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_do_en_o[0] None \
qspi_output_data_skew 0.4 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/tx_shift_reg_reg_33_/CP SF0_IO1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_do_o[1] None \
qspi_output_data_skew 0.4 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/qspi_do_en_o_reg_1_/CP SF0_IO1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_do_en_o[1] None \
qspi_output_data_skew 0.4 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/tx_shift_reg_reg_34_/CP SF0_IO2 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_do_o[2] None \
qspi_output_data_skew 0.4 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/qspi_do_en_o_reg_2_/CP SF0_IO2 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_do_en_o[2] None \
qspi_output_data_skew 0.4 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/tx_shift_reg_reg_35_/CP SF0_IO3 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_do_o[3] None \
qspi_output_data_skew 0.4 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/qspi_do_en_o_reg_2_/CP SF0_IO3 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_do_en_o[3] None \
qspi_output_data_skew 0.4 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/qspi_sck_o_pre_reg/CP SF0_SCK u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_sck_o None \
]

tproc_stc_skew_report $qspi_output_data_skew_list
tproc_stc_array2csv   $qspi_output_data_skew_list stc_check_skew.csv

set qspi_input_skew_list [list \
qspi_input_skew 0.5 SF0_IO0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/rx_shift_reg_reg_0_/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_di_i[0] None \
qspi_input_skew 0.5 SF0_IO1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/rx_shift_reg_reg_0_/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_di_i[1] None \
qspi_input_skew 0.5 SF0_IO1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/rx_shift_reg_reg_1_/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_di_i[1] None \
qspi_input_skew 0.5 SF0_IO2 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/rx_shift_reg_reg_2_/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_di_i[2] None \
qspi_input_skew 0.5 SF0_IO3 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_qspi_flashc/u_qspi_flashc_fsm/rx_shift_reg_reg_3_/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/qspi_di_i[3] None \
]

tproc_stc_skew_report $qspi_input_skew_list
tproc_stc_array2csv   $qspi_input_skew_list stc_check_skew.csv

    set ext_spi_output_skew_list [list \
ext_spi_output_skew 2.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/tx_shift_reg_reg_32_/CP SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_do_o[0] None \
ext_spi_output_skew 2.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/qspi_do_en_o_reg_0_/CP SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_do_en_o[0] None \
ext_spi_output_skew 2.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/tx_shift_reg_reg_33_/CP SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_do_o[1] None \
ext_spi_output_skew 2.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/qspi_do_en_o_reg_1_/CP SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_do_en_o[1] None \
ext_spi_output_skew 2.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/tx_shift_reg_reg_34_/CP KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_do_o[2] None \
ext_spi_output_skew 2.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/qspi_do_en_o_reg_2_/CP KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_do_en_o[2] None \
ext_spi_output_skew 2.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/tx_shift_reg_reg_35_/CP KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_do_o[3] None \
ext_spi_output_skew 2.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/qspi_do_en_o_reg_2_/CP KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_do_en_o[3] None \
ext_spi_output_skew 2.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/fsm_cs_reg_0_/CP SPI2_MOSI u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_cs_n_o None \
ext_spi_output_skew 2.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/qspi_sck_o_pre_reg/CP SPI2_CLK u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_sck_o None \
]

tproc_stc_skew_report $ext_spi_output_skew_list
tproc_stc_array2csv   $ext_spi_output_skew_list stc_check_skew.csv

    set ext_spi_output_data_skew_list [list \
ext_spi_output_data_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/tx_shift_reg_reg_32_/CP SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_do_o[0] None \
ext_spi_output_data_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/qspi_do_en_o_reg_0_/CP SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_do_en_o[0] None \
ext_spi_output_data_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/tx_shift_reg_reg_33_/CP SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_do_o[1] None \
ext_spi_output_data_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/qspi_do_en_o_reg_1_/CP SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_do_en_o[1] None \
ext_spi_output_data_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/tx_shift_reg_reg_34_/CP KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_do_o[2] None \
ext_spi_output_data_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/qspi_do_en_o_reg_2_/CP KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_do_en_o[2] None \
ext_spi_output_data_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/tx_shift_reg_reg_35_/CP KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_do_o[3] None \
ext_spi_output_data_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/qspi_do_en_o_reg_2_/CP KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_do_en_o[3] None \
ext_spi_output_data_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/qspi_sck_o_pre_reg/CP SPI2_CLK u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_sck_o None \
]

tproc_stc_skew_report $ext_spi_output_data_skew_list
tproc_stc_array2csv   $ext_spi_output_data_skew_list stc_check_skew.csv

set ext_spi_input_skew_list [list \
ext_spi_input_skew 1.2 SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/rx_shift_reg_reg_0_/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_di_i[0] None \
ext_spi_input_skew 1.2 SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/rx_shift_reg_reg_0_/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_di_i[1] None \
ext_spi_input_skew 1.2 SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/rx_shift_reg_reg_1_/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_di_i[1] None \
ext_spi_input_skew 1.2 KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/rx_shift_reg_reg_2_/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_di_i[2] None \
ext_spi_input_skew 1.2 KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_ext_qspi_flashc/u_qspi_flashc_fsm/rx_shift_reg_reg_3_/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ext_spi_di_i[3] None \
]

tproc_stc_skew_report $ext_spi_input_skew_list 
tproc_stc_array2csv   $ext_spi_input_skew_list stc_check_skew.csv

    set sdio_output_abt_skew_list [list \
sdio_output_abt_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/tx_data0_abt_reg/CP  SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data0_out None \
sdio_output_abt_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/tx_data3_abt_en_reg/CP KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data1_out None \
sdio_output_abt_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/tx_data1_abt_reg/CP KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data1_out None \
sdio_output_abt_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/tx_data3_abt_en_reg/CP KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out None \
sdio_output_abt_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/tx_data1_abt_reg/CP KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out None \
sdio_output_abt_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/tx_data3_abt_en_reg/CP SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out None \
sdio_output_abt_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/tx_data1_abt_reg/CP SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out None \
]

tproc_stc_skew_report $sdio_output_abt_skew_list
tproc_stc_array2csv   $sdio_output_abt_skew_list stc_check_skew.csv


    set sdio_output_posedge_skew_list [list \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/sig_tx_data0_reg/CP SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data0_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/sig_tx_data1_reg/CP KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data1_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/sig_tx_data2_reg/CP KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/sig_tx_data3_reg/CP SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/byte_cnt_d_reg_1_0_/CP SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data0_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/byte_cnt_d_neg_reg_0_/CPN SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data0_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/valid_state_d_reg_0_/CP SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data0_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/valid_state_neg_d_reg_0_/CPN SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data0_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/current_tx_state_d2_reg_0_/CP SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data0_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/current_tx_state_d2_reg_4_1_/CP SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data0_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/byte_cnt_d_reg_1_0_/CP KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data1_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/byte_cnt_d_neg_reg_0_/CPN KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data1_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/valid_state_d_reg_0_/CP KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data1_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/valid_state_neg_d_reg_0_/CPN KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data1_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/current_tx_state_d2_reg_0_/CP KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data1_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/current_tx_state_d2_reg_4_1_/CP KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data1_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/byte_cnt_d_reg_1_0_/CP KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/byte_cnt_d_neg_reg_0_/CPN KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/valid_state_d_reg_0_/CP KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/valid_state_neg_d_reg_0_/CPN KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/current_tx_state_d2_reg_0_/CP KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/current_tx_state_d2_reg_4_1_/CP KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/byte_cnt_d_reg_1_0_/CP SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/byte_cnt_d_neg_reg_0_/CPN SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/valid_state_d_reg_0_/CP SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/valid_state_neg_d_reg_0_/CPN SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/current_tx_state_d2_reg_0_/CP SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/current_tx_state_d2_reg_4_1_/CP SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/sig_tx_data0_en_reg/CP SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data0_out_en None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/sig_tx_data3_en_reg/CP KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data1_out_en None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_receive1/rx_dat2_en_reg/CP KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out_en None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/sig_tx_data3_en_reg/CP KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out_en None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_cmd_resp1/dat3_en_reg/CP SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out_en None \
sdio_output_posedge_skew 1.5 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/sig_tx_data3_en_reg/CP SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out_en None \
]

tproc_stc_skew_report $sdio_output_posedge_skew_list
tproc_stc_array2csv   $sdio_output_posedge_skew_list stc_check_skew.csv

    set sdio_output_negedge_skew_list [list \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/sig_tx_data0_neg_reg/CPN SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data0_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/sig_tx_data1_neg_reg/CPN KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data1_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/sig_tx_data2_neg_reg/CPN KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/sig_tx_data3_neg_reg/CPN SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/byte_cnt_d_reg_1_0_/CP SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data0_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/byte_cnt_d_neg_reg_0_/CPN SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data0_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/valid_state_d_reg_0_/CP SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data0_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/valid_state_neg_d_reg_0_/CPN SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data0_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/current_tx_state_d2_reg_0_/CP SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data0_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/current_tx_state_d2_reg_4_1_/CP SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data0_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/byte_cnt_d_reg_1_0_/CP KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data1_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/byte_cnt_d_neg_reg_0_/CPN KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data1_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/valid_state_d_reg_0_/CP KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data1_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/valid_state_neg_d_reg_0_/CPN KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data1_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/current_tx_state_d2_reg_0_/CP KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data1_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/current_tx_state_d2_reg_4_1_/CP KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data1_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/byte_cnt_d_reg_1_0_/CP KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/byte_cnt_d_neg_reg_0_/CPN KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/valid_state_d_reg_0_/CP KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/valid_state_neg_d_reg_0_/CPN KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/current_tx_state_d2_reg_0_/CP KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/current_tx_state_d2_reg_4_1_/CP KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/byte_cnt_d_reg_1_0_/CP SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/byte_cnt_d_neg_reg_0_/CPN SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/valid_state_d_reg_0_/CP SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/valid_state_neg_d_reg_0_/CPN SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/current_tx_state_d2_reg_0_/CP SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/current_tx_state_d2_reg_4_1_/CP SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_high_ctrl1/n_data0_en_reg/CPN SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data0_out_en None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_high_ctrl1/n_data3_en_reg/CPN KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data1_out_en None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_high_ctrl1/n_data2_rw_en_reg/CPN KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out_en None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_high_ctrl1/n_data3_en_reg/CPN KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data2_out_en None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_high_ctrl1/n_data3_high_en_reg/CPN SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out_en None \
sdio_output_negedge_skew 3.0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_high_ctrl1/n_data3_en_reg/CPN SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/ahb_iopad_sd_data3_out_en None \
]

tproc_stc_skew_report $sdio_output_negedge_skew_list
tproc_stc_array2csv   $sdio_output_negedge_skew_list stc_check_skew.csv


set sdio_input_posedge_skew_list [list \
sdio_input_posedge_skew 1.2 SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_receive1/sig_data0_in_reg/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/iopad_ahb_sd_data0_in None \
sdio_input_posedge_skew 1.2 SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_transmit1/sig_data0_reg/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/iopad_ahb_sd_data0_in None \
sdio_input_posedge_skew 1.2 KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_receive1/sig_data1_in_reg/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/iopad_ahb_sd_data1_in None \
sdio_input_posedge_skew 1.2 KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_receive1/sig_data2_in_reg/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/iopad_ahb_sd_data2_in None \
sdio_input_posedge_skew 1.2 SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_receive1/sig_data3_in_reg/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/iopad_ahb_sd_data3_in None \
]

tproc_stc_skew_report $sdio_input_posedge_skew_list
tproc_stc_array2csv   $sdio_input_posedge_skew_list stc_check_skew.csv

set sdio_input_negedge_skew_list [list \
sdio_input_negedge_skew 1.2 SPI2_MISO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_receive1/sig_data0_in_neg_reg/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/iopad_ahb_sd_data0_in None \
sdio_input_negedge_skew 1.2 KEYIN1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_receive1/sig_data1_in_neg_reg/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/iopad_ahb_sd_data1_in None \
sdio_input_negedge_skew 1.2 KEYOUT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_receive1/sig_data2_in_neg_reg/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/iopad_ahb_sd_data2_in None \
sdio_input_negedge_skew 1.2 SPI2_CSN u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_sd3_top/u_sd3_ctrl/u_receive1/sig_data3_in_neg_reg/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/iopad_ahb_sd_data3_in None \
]

tproc_stc_skew_report $sdio_input_negedge_skew_list
tproc_stc_array2csv   $sdio_input_negedge_skew_list stc_check_skew.csv

set spi0_input_skew_list [list \
spi0_input_skew 3.0 CAM_SPI_D1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_spi0/i_spi_camera_slavesync/cdnsspi_si_sync1/gen_sync_1__inst_async_reset_i_cdns_syncflop/cmind_sync_buf2_bit2_0__genblk1_sync2_rst0_sig_in_sync0_reg/cmind_uj_cell/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/spi0_miso_in None \
spi0_input_skew 3.0 CAM_SPI_D0 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_spi0/i_spi_camera_slavesync/cdnsspi_si_sync1/gen_sync_0__inst_async_reset_i_cdns_syncflop/cmind_sync_buf2_bit2_0__genblk1_sync2_rst0_sig_in_sync0_reg/cmind_uj_cell/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/spi0_mosi_in None \
spi0_input_skew 3.0 CAM_SPI_D2 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_spi0/i_spi_camera_slavesync/cdnsspi_si_sync1/gen_sync_2__inst_async_reset_i_cdns_syncflop/cmind_sync_buf2_bit2_0__genblk1_sync2_rst0_sig_in_sync0_reg/cmind_uj_cell/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/spi0_nss_in None \
spi0_input_skew 3.0 CAM_SPI_D3 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_spi0/i_spi_camera_slavesync/cdnsspi_si_sync1/gen_sync_3__inst_async_reset_i_cdns_syncflop/cmind_sync_buf2_bit2_0__genblk1_sync2_rst0_sig_in_sync0_reg/cmind_uj_cell/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/spi0_d3_in None \
spi0_input_skew 3.0 CAM_SPI_CLK u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_spi0/i_spi_camera_slavesync/cdnsspi_slave_clk_sync1/gen_sync_0__inst_async_reset_i_cdns_syncflop/cmind_sync_buf2_bit2_0__genblk1_sync2_rst0_sig_in_sync0_reg/cmind_uj_cell/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/spi0_sclk_in None \
]

tproc_stc_skew_report $spi0_input_skew_list
tproc_stc_array2csv   $spi0_input_skew_list stc_check_skew.csv

set spi2_input_skew_IIS_list [list \
spi2_input_skew_IIS 1.5 IISDO u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_spi2/i_cdnsspi_slavesync/cdnsspi_si_sync1/gen_sync_0__inst_async_reset_i_cdns_syncflop/cmind_sync_buf2_bit2_0__genblk1_sync2_rst0_sig_in_sync0_reg/cmind_uj_cell/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/spi2_mosi_in None \
spi2_input_skew_IIS 1.5 IISCLK u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_spi2/i_cdnsspi_slavesync/cdnsspi_slave_clk_sync1/gen_sync_0__inst_async_reset_i_cdns_syncflop/cmind_sync_buf2_bit2_0__genblk1_sync2_rst0_sig_in_sync0_reg/cmind_uj_cell/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/spi2_sclk_in None \
]

tproc_stc_skew_report $spi2_input_skew_IIS_list
tproc_stc_array2csv   $spi2_input_skew_IIS_list stc_check_skew.csv

set spi2_input_skew_EXTINT_list [list \
spi2_input_skew_EXTINT 1.5 EXTINT1 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_spi2/i_cdnsspi_slavesync/cdnsspi_si_sync1/gen_sync_0__inst_async_reset_i_cdns_syncflop/cmind_sync_buf2_bit2_0__genblk1_sync2_rst0_sig_in_sync0_reg/cmind_uj_cell/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/spi2_mosi_in None \
spi2_input_skew_EXTINT 1.5 EXTINT3 u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_spi2/i_cdnsspi_slavesync/cdnsspi_slave_clk_sync1/gen_sync_0__inst_async_reset_i_cdns_syncflop/cmind_sync_buf2_bit2_0__genblk1_sync2_rst0_sig_in_sync0_reg/cmind_uj_cell/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/spi2_sclk_in None \
]

tproc_stc_skew_report $spi2_input_skew_EXTINT_list
tproc_stc_array2csv   $spi2_input_skew_EXTINT_list stc_check_skew.csv

set spi2_input_skew_SPI2_list [list \
spi2_input_skew_SPI2 1.5 SPI2_MOSI u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_spi2/i_cdnsspi_slavesync/cdnsspi_si_sync1/gen_sync_0__inst_async_reset_i_cdns_syncflop/cmind_sync_buf2_bit2_0__genblk1_sync2_rst0_sig_in_sync0_reg/cmind_uj_cell/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/spi2_mosi_in None \
spi2_input_skew_SPI2 1.5 SPI2_CLK u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/u_ap_sys_peri_top/u_spi2/i_cdnsspi_slavesync/cdnsspi_slave_clk_sync1/gen_sync_0__inst_async_reset_i_cdns_syncflop/cmind_sync_buf2_bit2_0__genblk1_sync2_rst0_sig_in_sync0_reg/cmind_uj_cell/D u_digital_top/u_ap_sys_pwr_wrap/u_ap_sys_top/spi2_sclk_in None \
]

tproc_stc_skew_report $spi2_input_skew_SPI2_list
tproc_stc_array2csv   $spi2_input_skew_SPI2_list stc_check_skew.csv

